[workspace]
members = ["core", "bin/{{project-name}}"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["{{author}} <{{email}}>"]
repository = "https://github.com/{{org}}/{{ project-name | kebab_case }}"
edition = "2024"
publish = false

[workspace.dependencies]
atb-types = { version = "2", features = [
  "jwt",
] }
atb-tokio-ext = "2"
atb-fixtures-utils = { version = "2", features = [
  "jwt",
] }
atb-logging = "2"

temporalio-client = "0.7"
temporalio-common = "0.7"
temporalio-macros = "0.7"
temporalio-sdk = "0.7"
temporalio-workflow = "0.7"

strum = { version = "0.27", features = ["derive"] }
num_enum = { version = "0.7.5" }
tracing = { version = "0.1" }
anyhow = { version = "1" }
thiserror = { version = "2" }
serde = { version = "1" }
serde_json = { version = "1" }
cfg-if = { version = "1" }
once_cell = { version = "1" }
rand = { version = "0.9" }
base64 = { version = "0.22" }
reqwest = { version = "0.13", default-features = false, features = [
  "socks",
  "stream",
  "json",
  "rustls",
] }
tokio = { version = "1", features = [
  "signal",
  "rt-multi-thread",
  "net",
  "time",
  "macros",
  "sync",
] }
sqlx = { version = "0.8", default-features = false, features = [
  "runtime-tokio-rustls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "json",
  "bigdecimal",
  "rust_decimal",
  "bit-vec",
  "any",
  "migrate",
  "ipnetwork",
] }
ipnetwork = "0.21.1"
futures = "0.3.31"
futures-channel = { version = "0.3" }
futures-util = "0.3"
regex = { version = "1.11.1" }
rust_decimal = { version = "1.37.2", features = [
  "serde-with-arbitrary-precision",
] }
